// Section: Data Source and Description
#import "../../template.typ": extended

== Data Source and Description

=== Dataset Origin

The dataset analyzed in this study was generated by the *INOHAC AMR Project Two* research team as part of an environmental antimicrobial resistance surveillance initiative. The present study does not involve primary sampling or laboratory experimentation. All analyses are conducted as a *secondary analysis* of phenotypic AST data collected by the source project.
The dataset comprises AST results for bacterial isolates obtained from environmental and aquaculture-associated sources across three geographic regions in the Philippines: Eastern Visayas, Central Luzon, and the Bangsamoro Autonomous Region in Muslim Mindanao (BARMM).

=== Sample Source Categories

Isolates originate from environmental matrices representing the *Water–Fish interface* within the broader Water–Fish–Human nexus. These source categories capture exposure pathways relevant to environmental AMR dissemination and are used exclusively as contextual metadata during interpretation. Source categories are listed in @tab:sample-source-categories.

#figure(
  table(
    columns: 3,
    table.header[*Source Code*][*Source Type*][*Description*],
    [DW], [Drinking Water], [Community water sources],
    [LW], [Lake Water], [Natural water bodies],
    [RW], [River Water], [Flowing water systems],
    [EWU], [Effluent Water (Untreated)], [Hospital or facility discharge (Human interface)],
    [EWT], [Effluent Water (Treated)], [Processed effluent discharge (Human interface)],
    [FB, FG, FT, FK], [Fish], [Banak, Gusaw, Tilapia, Kaolang],
  ),
  caption: [Sample Source Categories.#extended[ Isolates originate from environmental matrices representing the Water–Fish interface within the broader Water–Fish–Human nexus.]],
) <tab:sample-source-categories>

*Note:* While direct human clinical isolates are not included, effluent water samples (EWU, EWT) represent the anthropogenic component of the nexus, capturing resistance patterns potentially influenced by human antibiotic use and healthcare facility discharge.

=== Isolate Identification Convention

Each isolate is assigned a structured alphanumeric identifier encoding species, geographic origin, source type, replicate number, and colony number using the format:

#raw(block: true, lang: none, "[Species Prefix]_[Region][Site][Source][Replicate][Colony]")

This convention enables systematic metadata parsing while preserving traceability throughout the analytical pipeline. The replicate and colony identifiers include 'R' and 'C' prefixes respectively (e.g., R1C1). Sample isolate records from the unified raw dataset are presented in @tab:sample-isolates-raw.

#rotate(-90deg, reflow: true)[
  #figure(
    table(
      columns: (
        0.6fr,
        1.2fr,
        1fr,
        0.8fr,
        0.4fr,
        0.4fr,
        0.4fr,
        0.4fr,
        0.4fr,
        0.4fr,
        0.4fr,
        0.4fr,
        0.4fr,
        0.4fr,
        0.4fr,
        0.6fr,
      ),
      align: center,
      stroke: 0.5pt,
      inset: 3pt,

      // Header row
      [*Isolate No.*],
      [*Species*],
      [*Region*],
      [*Source*],
      [*AM*],
      [*AMC*],
      [*CF*],
      [*IPM*],
      [*GM*],
      [*AN*],
      [*TE*],
      [*DO*],
      [*C*],
      [*SXT*],
      [*ESBL*],
      [*MAR*],

      // Data rows - 20 diverse isolates from unified_raw_dataset (n=583)
      // BARMM - Hospital Effluent
      [1], [_E. coli_], [BARMM], [EWU], [R], [I], [S], [S], [S], [S], [S], [S], [S], [R], [NEG], [0.09],
      [2], [_K. pneumoniae_], [BARMM], [EWU], [R], [S], [S], [S], [S], [S], [S], [S], [S], [S], [NEG], [0.05],
      [3], [_E. coli_], [BARMM], [EWT], [S], [S], [S], [S], [S], [S], [R], [S], [S], [S], [NEG], [0.14],
      // BARMM - Drinking Water
      [4], [_E. coli_], [BARMM], [DW], [R], [S], [S], [S], [S], [S], [R], [R], [S], [R], [NEG], [0.18],
      [5], [_K. pneumoniae_], [BARMM], [DW], [R], [S], [R], [S], [R], [S], [R], [R], [S], [R], [POS], [0.38],
      // BARMM - Lake Water
      [6], [_K. pneumoniae_], [BARMM], [LW], [R], [R], [R], [S], [R], [S], [R], [R], [S], [R], [NEG], [0.50],
      [7], [_V. cholerae_], [BARMM], [LW], [R], [S], [-], [S], [-], [S], [S], [S], [-], [S], [-], [0.07],
      // BARMM - Water (Enterobacter)
      [8], [_E. cloacae_], [BARMM], [DW], [-], [R], [R], [S], [S], [S], [S], [S], [S], [S], [-], [0.15],
      [9], [_E. aerogenes_], [BARMM], [DW], [-], [R], [R], [S], [S], [S], [S], [S], [S], [S], [-], [0.14],
      // Region III - River Water
      [10], [_E. coli_], [Region III], [RW], [R], [S], [S], [S], [S], [S], [S], [S], [S], [S], [NEG], [0.09],
      [11], [_K. pneumoniae_], [Region III], [RW], [R], [S], [S], [S], [S], [S], [R], [R], [R], [R], [NEG], [0.23],
      [12], [_E. cloacae_], [Region III], [RW], [-], [R], [R], [S], [S], [S], [S], [S], [S], [S], [-], [0.15],
      // Region III - Fish Tilapia
      [13], [_E. coli_], [Region III], [FT], [S], [S], [S], [S], [S], [S], [S], [S], [S], [S], [NEG], [0.00],
      [14], [_E. aerogenes_], [Region III], [FT], [-], [R], [R], [S], [S], [S], [S], [S], [S], [S], [-], [0.14],
      // Region III - Fish Gusaw
      [15], [_K. pneumoniae_], [Region III], [FG], [R], [S], [S], [S], [S], [S], [R], [R], [R], [R], [NEG], [0.23],
      [16], [_E. cloacae_], [Region III], [FG], [-], [R], [R], [S], [S], [S], [S], [S], [S], [S], [-], [0.15],
      // Region VIII - Drinking Water
      [17], [_E. coli_], [Region VIII], [DW], [S], [S], [S], [S], [S], [S], [S], [S], [S], [S], [NEG], [0.00],
      // Region VIII - Fish Gusaw
      [18], [_E. coli_], [Region VIII], [FG], [S], [S], [S], [S], [S], [S], [R], [R], [S], [R], [NEG], [0.18],
      [19], [_K. pneumoniae_], [Region VIII], [FG], [R], [S], [S], [S], [S], [S], [S], [S], [S], [S], [NEG], [0.05],
      // Region VIII - Fish (with resistance)
      [20], [_E. coli_], [Region VIII], [FG], [R], [S], [S], [S], [S], [S], [R], [R], [R], [R], [NEG], [0.18],
    ),
    caption: [Sample Isolate Records from the Unified Raw Dataset.#extended[ (n = 583). AM: Ampicillin, AMC: Amoxicillin/Clavulanic Acid, CF: Cefalexin, IPM: Imipenem, GM: Gentamicin, AN: Amikacin, TE: Tetracycline, DO: Doxycycline, C: Chloramphenicol, SXT: Trimethoprim/Sulfamethoxazole. S: Susceptible, I: Intermediate, R: Resistant, -: Not tested. Source codes: DW: Drinking Water, LW: Lake Water, RW: River Water, EWU/EWT: Effluent Water, FT: Fish Tilapia, FG: Fish Gusaw.]],
  ) <tab:sample-isolates-raw>
]

=== Antimicrobial Panel

Phenotypic AST data consists of a panel of *22 antibiotics spanning 12 antimicrobial classes*, including an ESBL screening indicator. The antimicrobial panel is summarized in @tab:antimicrobial-panel.

#figure(
  table(
    columns: 2,
    table.header[*Antimicrobial Class*][*Antibiotics*],
    [1. Penicillins], [Ampicillin],
    [2. β-lactam/β-lactamase inhibitors], [Amoxicillin/Clavulanic Acid],
    [3. Cephalosporins (1st gen.)], [Cefalexin, Cefalotin],
    [4. Cephalosporins (3rd/4th gen.)], [Cefpodoxime, Cefotaxime, Cefovecin, Ceftiofur],
    [5. Advanced cephalosporins], [Ceftaroline, Ceftazidime/Avibactam],
    [6. Carbapenems], [Imipenem],
    [7. Aminoglycosides], [Amikacin, Gentamicin, Neomycin],
    [8. Quinolones / Fluoroquinolones], [Nalidixic Acid, Enrofloxacin, Marbofloxacin, Pradofloxacin],
    [9. Tetracyclines], [Doxycycline, Tetracycline],
    [10. Nitrofurans], [Nitrofurantoin],
    [11. Phenicols], [Chloramphenicol],
    [12. Folate pathway inhibitors], [Trimethoprim/Sulfamethoxazole],
    [Resistance indicator], [ESBL screening],
  ),
  caption: [Antimicrobial Panel Composition.#extended[ (12 Classes, 22 Antibiotics). The panel spans major antimicrobial classes including Penicillins, Cephalosporins, Carbapenems, and Aminoglycosides.]],
) <tab:antimicrobial-panel>
