// 1.1 Background of the Study

== Background of the Study

Antimicrobial resistance (AMR) represents one of the most pressing global health challenges of the 21st century. The World Health Organization has declared AMR among the top ten threats to global health, with an estimated 1.27 million deaths directly attributable to bacterial AMR in 2019 alone @who2025glass. Without coordinated intervention, AMR-related mortality is projected to reach 10 million deaths annually by 2050, surpassing cancer as a leading cause of death worldwide @oneill2016review.

The Philippines, as a rapidly developing archipelagic nation with extensive aquaculture industries and diverse healthcare systems, faces unique challenges in AMR surveillance and control. The country's position within the Indo-Pacific region, a recognized hotspot for emerging infectious diseases, places it at elevated risk for resistance dissemination across human, animal, and environmental interfaces @ng2025philippines. The Antimicrobial Resistance Surveillance Program (ARSP), established in 1988, has documented concerning trends including rising carbapenem-resistant Enterobacteriaceae and extended-spectrum β-lactamase (ESBL)-producing organisms in clinical settings @arsp2024.

Recent advances in machine learning (ML) offer promising opportunities to enhance AMR surveillance capabilities. Data-driven approaches including clustering algorithms, random forest classifiers, and neural networks have demonstrated utility in identifying resistance patterns, predicting phenotypes from genotypes, and stratifying patient risk @sakagianni2024datadriven @parthasarathi2024mlstrategy. However, the application of these methods to environmental data, particularly in the Philippines, remains limited @ng2025philippines, especially in resource-constrained settings where phenotypic data predominate over genomic information.

The Integrated One Health Approach to AMR Containment (INOHAC) AMR Project Two, implemented across three Philippine regions (BARMM, Central Luzon, and Eastern Visayas), provides a unique dataset spanning the water-fish-human nexus @abamo2024inohac. The project focused on mapping antibiotic-resistant _Escherichia coli_, _Salmonella_ spp., _Shigella_ spp., and _Vibrio cholerae_, which are pathogenic bacteria and primary etiologic agents in bacterial diarrhea, across water resources, fish biota, and human populations.

Antimicrobial resistance is fundamentally a One Health issue, where human health, animal health, and environmental health are inextricably linked. Antibiotic use in any sector, whether in human hospitals, agricultural livestock, or through environmental release, drives the selection and evolution of resistance genes, which can then flow across all other sectors. The INOHAC Project Two theoretical framework identifies three major interconnected systems through which resistance disseminates. In the healthcare sector, hospitals release resistant bacteria through waste streams into the environment via nosocomial dissemination pathways. In agricultural settings, resistant bacteria develop due to antibiotic use in livestock operations, subsequently contaminating food products and farm waste. The environment, comprising water, sewage, and soil, acts as a mixing vessel, receiving contamination from both hospitals and farms, and then transmitting resistant organisms back to humans through water consumption and to farms through irrigation.

This interconnected framework underscores the necessity of surveillance across all three systems to understand the intricate dynamics among the water environment, fish biota, and humans. Identifying AMR sources within this nexus enables the development of comprehensive action plans to break the chain of AMR spread. The project addresses critical factors including waste disposal practices, open defecation, limited knowledge on AMR, inadequate water, sanitation, and hygiene (WASH) programs, and the lack of proper coordination among stakeholders such as academe, local government units (LGUs), and health and business sectors @franklin2024onehealth.

Pattern recognition, a core computer science discipline, provides a methodological framework for analyzing such complex datasets. Unlike traditional categorical labels (e.g., "multi-drug resistant"), pattern recognition algorithms discover latent structures in resistance profiles without predefined assumptions. Hierarchical clustering groups isolates by phenotypic similarity, while supervised methods like Random Forest validate whether discovered patterns represent coherent groupings. This approach bridges raw laboratory data and actionable epidemiological insights, enabling identification of resistance phenotypes and co-resistance relationships hidden in high-dimensional susceptibility data.
